### ISSUE TITLE
rand-runs not running

### ISSUE THREAD

**Issue by fs-craig** [fsdonks/m4#45]
(def path "/home/craig/runs/big_test/base-testdata-v7.xlsx") ;;straight from notional
(def phases [["comp" 1 821] ["phase-1" 822 5000]])
(def results (rand-runs proj :reps 1 :phases phases
                               :lower 0 :upper 1.5
                               :compo-lengths default-compo-lengths))
Execution error (NullPointerException) at marathon.analysis.random/ac-supply-reduction-experiments (random.clj:206).
null

**Comment by fs-tom** [comment]
Input passes with notional data in 4.1.9
